[colors.bright]
black = "#cdc6df"
blue = "#657b83"
cyan = "#586e75"
green = "#93a1a1"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#002b36"
yellow = "#839496"

[colors.cursor]
cursor = "#586e75"
text = "#fdf6e3"

[colors.normal]
black = "#eee8d5"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#073642"
yellow = "#b58900"

[colors.primary]
background = "#fdf5e3"
bright_foreground = "#073642"
foreground = "#506879"

[cursor.style]
blinking = "Off"
shape = "Underline"

[dracula.bright]
black = "#6272a4"
blue = "#d6acff"
cyan = "#a4ffff"
green = "#69ff94"
magenta = "#ff92df"
red = "#ff6e6e"
white = "#ffffff"
yellow = "#ffffa5"

[dracula.cursor]
cursor = "CellForeground"
text = "CellBackground"

[dracula.footer_bar]
background = "#282a36"
foreground = "#f8f8f2"

[dracula.hints.end]
background = "#282a36"
foreground = "#f1fa8c"

[dracula.hints.start]
background = "#f1fa8c"
foreground = "#282a36"

[dracula.line_indicator]
background = "None"
foreground = "None"

[dracula.normal]
black = "#21222c"
blue = "#bd93f9"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#f8f8f2"
yellow = "#f1fa8c"

[dracula.primary]
background = "#282a36"
bright_foreground = "#ffffff"
foreground = "#f8f8f2"

[dracula.search.focused_match]
background = "#ffb86c"
foreground = "#44475a"

[dracula.search.matches]
background = "#50fa7b"
foreground = "#44475a"

[dracula.selection]
background = "#44475a"
text = "CellForeground"

[dracula.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[env]
TERM = "alacritty"

[font]
builtin_box_drawing = true
size = 17

[font.normal]
family = "monospace"
style = "Regular"

[papercolor_light.bright]
black = "#bcbcbc"
blue = "#d75f00"
cyan = "#005faf"
green = "#d70087"
magenta = "#d75f00"
red = "#d70000"
white = "#005f87"
yellow = "#8700af"

[papercolor_light.cursor]
cursor = "#666666"
text = "#eeeeee"

[papercolor_light.normal]
black = "#e8e8e8"
blue = "#0087af"
cyan = "#005f87"
green = "#008700"
magenta = "#878787"
red = "#af0000"
white = "#666666"
yellow = "#5f8700"

[papercolor_light.primary]
background = "#e8e8e8"
foreground = "#111111"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
dynamic_title = true
gtk_theme_variant = "dark"
opacity = 0.99
startup_mode = "Maximized"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0

